# Generated by Django 4.1.2 on 2023-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='logo',
        ),
        migrations.AddField(
            model_name='myuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='User surname'),
        ),
    ]
