# Generated by Django 4.1.2 on 2023-02-25 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Department haqqinda')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departamentler',
            },
        ),
        migrations.CreateModel(
            name='DepartmentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Position adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Position haqqinda')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionlar',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Position adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Position haqqinda')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project adi')),
                ('employee_number', models.PositiveIntegerField(verbose_name='Isci sayi')),
                ('industry', models.CharField(choices=[('IT', 'IT'), ('Construction', 'Construction')], max_length=30, verbose_name='Company field')),
                ('companyleader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projectler',
            },
        ),
        migrations.CreateModel(
            name='ProjectDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Department haqqinda')),
                ('employee_number', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.project')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departamentler',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bacariq adi')),
                ('skilltype', models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard')], max_length=5, null=True, verbose_name='Bacariq tipi')),
            ],
            options={
                'verbose_name': 'Bacariq',
                'verbose_name_plural': 'Bacariqlar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='User adi')),
                ('surname', models.CharField(max_length=20, verbose_name='User soyadi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wizard.projectdepartment', verbose_name='User departmenti')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wizard.departmentposition', verbose_name='User position')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.project')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Skill agirligi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='wizard.department')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='wizard.skill')),
            ],
            options={
                'verbose_name': 'Skill weight',
                'verbose_name_plural': 'Skill weights',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userskill', to='wizard.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='wizard.user')),
            ],
        ),
        migrations.CreateModel(
            name='SkillNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.projectdepartment')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.departmentposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.skill')),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normalar',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSkillNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.PositiveIntegerField(verbose_name='norm for depnorm')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.department', verbose_name='Department for depnorm')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentskillnorm', to='wizard.position', verbose_name='Position for depnorm')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.skill', verbose_name='Skill for depnorm')),
            ],
            options={
                'verbose_name': 'Bacariq normasi',
                'verbose_name_plural': 'Bacariq normalari',
                'ordering': ['-norm'],
            },
        ),
        migrations.AddField(
            model_name='departmentposition',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.projectdepartment'),
        ),
    ]
