# Generated by Django 4.1.2 on 2023-02-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentskillnorm',
            name='position',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='departmentskillnorm', to='wizard.position', verbose_name='Position for depnorm'),
            preserve_default=False,
        ),
    ]
