# Generated by Django 4.1.2 on 2023-03-23 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainskill',
            name='department',
        ),
        migrations.AddField(
            model_name='mainskill',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wizard.departmentposition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectdepartment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='wizard.project'),
        ),
        migrations.AlterField(
            model_name='skillnorm',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skillnorm', to='wizard.departmentposition'),
        ),
    ]
