# Generated by Django 4.1.2 on 2023-02-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norm', '0001_initial'),
        ('wizard', '0002_alter_departmentskillnorm_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentskillnorm',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentskillnorm',
            name='position',
        ),
        migrations.RemoveField(
            model_name='departmentskillnorm',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='department',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='skill',
        ),
        migrations.AlterModelOptions(
            name='departmentposition',
            options={'verbose_name': 'Company position', 'verbose_name_plural': 'Company positions'},
        ),
        migrations.AlterModelOptions(
            name='projectdepartment',
            options={'verbose_name': 'Company departamenti', 'verbose_name_plural': 'Company departamentleri'},
        ),
        migrations.AlterModelOptions(
            name='skillnorm',
            options={'verbose_name': 'Sirket normasi', 'verbose_name_plural': 'Sirket normalari'},
        ),
        migrations.AlterField(
            model_name='skillnorm',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norm.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userskill', to='norm.skill'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentSkillNorm',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
