# Generated by Django 4.1.2 on 2023-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_rename_skill_mainskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hirponorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255, verbose_name='Bacariq')),
                ('skilltype', models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard')], max_length=5, null=True, verbose_name='skilltype')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('norm', models.IntegerField()),
            ],
        ),
    ]
