# Generated by Django 4.1.2 on 2023-03-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wizard', '0003_remove_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='companyleader',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='User adi')),
                ('last_name', models.CharField(max_length=20, verbose_name='User soyadi')),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('hire_date', models.DateField(auto_now_add=True, null=True)),
                ('is_systemadmin', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wizard.departmentposition', verbose_name='User position')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='wizard.project')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-position'],
            },
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='wizard.employee'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
