# Generated by Django 4.1.7 on 2023-03-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_hirponorms'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainskill',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='wizard.projectdepartment'),
            preserve_default=False,
        ),
    ]
