# Generated by Django 4.1.2 on 2023-03-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_remove_project_companyleader_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='user',
            new_name='Employee',
        ),
    ]
