# Generated by Django 4.2 on 2023-04-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_alter_userskill_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptency', to='wizard.allscores'),
        ),
    ]
