# Generated by Django 4.1.2 on 2023-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_alter_departmentposition_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdepartment',
            name='employee_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
