# Generated by Django 4.1.2 on 2023-03-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_alter_projectdepartment_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillnorm',
            name='department',
        ),
        migrations.AlterField(
            model_name='departmentposition',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentpositions', to='wizard.projectdepartment'),
        ),
    ]
