# Generated by Django 4.1.7 on 2023-03-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainskill',
            name='norm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SkillNorm',
        ),
    ]
