# Generated by Django 4.1.2 on 2023-03-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_employee_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainskill',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
