# Generated by Django 4.1.2 on 2023-04-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0010_project_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='leader',
            new_name='companyLeader',
        ),
    ]
