# Generated by Django 4.1.2 on 2023-04-09 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wizard', '0011_rename_leader_project_companyleader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userskill',
            old_name='Employee',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='weight',
        ),
        migrations.AddField(
            model_name='departmentposition',
            name='report_to',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departmentpositions', to='wizard.projectdepartment'))), null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.departmentposition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='positionName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='wizard.departmentposition', verbose_name='position level'),
        ),
        migrations.AlterField(
            model_name='project',
            name='companyLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.project')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='Evaluation_frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.period')),
            ],
        ),
        migrations.AddField(
            model_name='userskill',
            name='evaluation_frequency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='freq', to='wizard.evaluation_frequency'),
            preserve_default=False,
        ),
    ]
