# Generated by Django 4.1.2 on 2023-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0013_period_period_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(max_length=30, verbose_name='Company field'),
        ),
    ]
