# Generated by Django 4.2 on 2023-04-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0014_alter_project_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.CharField(choices=[('IT', 'IT'), ('Construction', 'Construction')], max_length=30, verbose_name='Company field'),
        ),
    ]
