# Generated by Django 4.2 on 2023-04-13 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0015_employee_phone_employee_report_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentposition',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizard.departmentposition'),
        ),
    ]
