# Generated by Django 4.1.2 on 2023-02-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Department adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Department haqqinda')),
            ],
            options={
                'verbose_name': 'Main Department',
                'verbose_name_plural': 'Main Departments',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Position adi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Position haqqinda')),
            ],
            options={
                'verbose_name': 'Main Position',
                'verbose_name_plural': 'Main Positions',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bacariq adi')),
                ('skilltype', models.CharField(blank=True, choices=[('Soft', 'Soft'), ('Hard', 'Hard')], max_length=5, null=True, verbose_name='Bacariq tipi')),
            ],
            options={
                'verbose_name': 'Main SKill',
                'verbose_name_plural': 'Main Skills',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(verbose_name='Skill agirligi')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='norm.department')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='norm.skill')),
            ],
            options={
                'verbose_name': 'Main Skill weight',
                'verbose_name_plural': 'Main Skill weights',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSkillNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norm', models.PositiveIntegerField(verbose_name='norm for depnorm')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norm.department', verbose_name='Department for depnorm')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departmentskillnorm', to='norm.position', verbose_name='Position for depnorm')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norm.skill', verbose_name='Skill for depnorm')),
            ],
            options={
                'verbose_name': 'Main Skill norm',
                'verbose_name_plural': 'Main Skill norms',
            },
        ),
    ]
