# Generated by Django 4.1.2 on 2023-02-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='department',
        ),
    ]
